Models/Order.cs
using System;
using System.Collections.Generic;

namespace Wahama
{
    public partial class Order
    {
        public int Id { get; set; }        
        public int UserId { get; set; } // Для сопоставления с корзиной
        public int CheckId { get; set; }               
        public Check Check { get; set; }
       
    }
}

Models/ShoppingCart.cs
using System;
using System.Collections.Generic;

namespace Wahama
{
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int UserId { get; set; }

        public Product Product { get; set; }
        public ICollection<Order> Order { get; set; }
    }
}

ViewModels/OrderViewModel.cs
using Microsoft.EntityFrameworkCore.Query;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wahama.Models
{
    public class OrderViewModel
    {
        public Order Order { get; set; }
        public Dictionary<int, string> ImageSources { get; set; }
        public Customer Customer { get; set; }
        public Address Address { get; set; }
        public Check Check { get; set; }
        public IEnumerable<ShoppingCart> CartItem { get; set; }
        public IIncludableQueryable<Product, ProductType> Products { get; set; }
    }
}

Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Wahama.Models;

namespace Wahama.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly WarhammerContext _context;

        public ShoppingCartsController(WarhammerContext context)
        {
            _context = context;
        }

        // Получение Id из таблицы Users по имени текущего пользователя
        public int GetUserId()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return _context.Users.Where(p => p.Login == HttpContext.Request.Cookies["UnauthorizedId"]).Select(p => p.Id).FirstOrDefault();
            }
            else
            {
                return _context.Users.Where(p => p.Login == User.Identity.Name).Select(p => p.Id).FirstOrDefault();
            }
        }

        // Подсчёт суммы покупок в корзине пользователя
        public int GetTotalCost()
        {
            int userId = GetUserId();
            int totalCost = 0;
            var userShoppingCart = _context.ShoppingCart.Where(p => p.UserId == userId).Include(s => s.Product).ToList();
            foreach (var item in userShoppingCart)
            {
                totalCost += item.Quantity * item.Product.Price;
            }
            return totalCost;
        }

        #region Cart
        // Корзина
        public IActionResult Index()
        {
            var product = _context.Product.Include(p => p.ProductFraction).Include(p => p.ProductType);
            var cartItems = _context.ShoppingCart.Include(s => s.Product).Where(p => p.UserId == GetUserId());
            Dictionary<int, string> productImages = GetImagesByIds();
            CartItemViewModel pvm = new CartItemViewModel { ImageSources = productImages, CartItem = cartItems, Products = product };
            return View(pvm);
        }

        [HttpPost]
        // Добавление в корзину
        public void AddToCart(int quantity, int productId)
        {
            int userId = GetUserId();
            if (ShoppingCartExists(productId)) // Если товар уже существует, то увеличивается количество, а если нет, то создается новый
            {
                ShoppingCart alreadyExistedItem = _context.ShoppingCart.Where(p => p.ProductId == productId && p.UserId == userId).SingleOrDefault();
                alreadyExistedItem.Quantity += quantity;
                _context.Update(alreadyExistedItem);
            }
            else
            {
                ShoppingCart shoppingCartItem = new ShoppingCart { ProductId = productId, Quantity = quantity, UserId = userId };
                _context.Add(shoppingCartItem);
            }
            _context.SaveChanges();
        }

        // Удаление из корзины отдельного товара
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int? quantityDifference, int productId)
        {
            // Если передать quantityDifference == null, то товар просто удалится, если нет, то изменится количество
            int userId = GetUserId();
            ShoppingCart alreadyExistedItem = _context.ShoppingCart.Where(p => p.ProductId == productId && p.UserId == userId).SingleOrDefault();
            if ((quantityDifference == null) || ((alreadyExistedItem.Quantity + quantityDifference) <= 0))
            {
                alreadyExistedItem.Quantity = 0;
            }
            else
            {
                alreadyExistedItem.Quantity += (int)quantityDifference;
            }
            if (alreadyExistedItem.Quantity == 0)
            {
                _context.Remove(alreadyExistedItem);
            }
            else
            {
                _context.Update(alreadyExistedItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // Перенос товаров, которые положили в корзину, будучи незалогиненным, в аккаунт
        public void ImportUnauthorizedCartToAccount()
        {
            IEnumerable<ShoppingCart> unauthorizedItemsList = _context.ShoppingCart.Where(p => p.UserId == _context.Users.Where(x => x.Login == HttpContext.Request.Cookies["UnauthorizedID"])
            .Select(z => z.Id).FirstOrDefault()).ToList();
            foreach (var item in unauthorizedItemsList)
            {
                item.UserId = GetUserId();
                _context.Update(item); 
                _context.SaveChanges();
            }
        }
        private bool ShoppingCartExists(int productId)
        {
            return _context.ShoppingCart.Any(e => e.ProductId == productId && e.UserId == GetUserId());
        }
        // Получение фото для каждого товара
        public Dictionary<int, string> GetImagesByIds()
        {
            using (var context = new WarhammerContext())
            {
                return context.ProductImage.ToDictionary(key => key.ProductId, value => value.ImageSource);
            }
        }
        #endregion
        #region Order
        // Оформление заказа
        public IActionResult Order()
        {
            var product = _context.Product.Include(p => p.ProductFraction).Include(p => p.ProductType);
            var cartItems = _context.ShoppingCart.Include(s => s.Product).Where(p => p.UserId == GetUserId());
            var address = new Address();
            var customer = new Customer();
            var check = new Check();
            var order = new Order();
            ViewBag.Total = GetTotalCost();

            Dictionary<int, string> productImages = GetImagesByIds();
            OrderViewModel ovm = new OrderViewModel { ImageSources = productImages, 
                CartItem = cartItems,
                Products = product, 
                Address = address, 
                Customer = customer,
                Order = order,
                Check = check
            };
            return View(ovm);
        }


        // Формируется заказ на основе данных формы
        public IActionResult MakeOrder(Customer customer, Address address)
        {
            int customerId = AddCustomerAndGetId(customer, address);
            var check1 = new Check
            {
                CustomerId = customerId,
                Date = DateTime.Now,
                IsPaid = false,
                PaymentMethodId = 1,
                Total = GetTotalCost()
            };
            _context.Check.Add(check1);
            _context.SaveChanges();

            _context.Order.Add(new Wahama.Order
            {

                UserId = _context.Users
                .Where(p => p.Login == User.Identity.Name)
                .Select(t => t.Id)
                .FirstOrDefault(),
                CheckId = check1.Id
            });
            _context.SaveChanges();
            return RedirectToAction("OrderSuccess");
        }

        // Создается адрес, клиент и возвращается его Id
        public int AddCustomerAndGetId(Customer customer, Address address)
        {
            Address thisAddress = new Address
            {
                Country = address.Country,
                City = address.City,
                Street = address.City,
                Station = address.Station,
                Building = address.Building,
                Flat = address.Flat,
                Floor = address.Floor,
                Zip = address.Zip
            };
            _context.Address.Add(thisAddress);
            _context.SaveChanges(); // Сначала создается адрес, потом сохраняется БД, берется айди и создается с ним Customer
            

            Customer customer1 = new Customer
            {
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                Phone = customer.Phone,
                AddressId = thisAddress.Id
            };
            _context.Customer.Add(customer1);
            _context.SaveChanges();
            return customer1.Id;
        }
        // View: заказ успешно оформлен
        public IActionResult OrderSuccess()
        {
            ViewBag.OrderId = _context.Order.Where(p => p.UserId == GetUserId()).Select(p => p.Id).FirstOrDefault();
            return View();
        }
        #endregion
    }
}

Views/ShoppingCarts/Create.cshtml
@model Wahama.ShoppingCart

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ShoppingCarts/Delete.cshtml
@model Wahama.ShoppingCart

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ShoppingCarts/Details.cshtml
@model Wahama.ShoppingCart

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ShoppingCarts/Edit.cshtml
@model Wahama.ShoppingCart

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ShoppingCarts/Index.cshtml
@model CartItemViewModel

@{
    ViewData["Title"] = "Index";
}
<style>
    .table td {
        vertical-align: middle;
    }

    .table th {
        width: 15%;
    }

    a {
        cursor: pointer;
    }

    input {
        padding-left: .5rem;
    }

    h2 {
        padding-bottom: 1.5rem;
    }

    h3 {
        margin-top: 1.5rem;
        padding-bottom: 1rem
    }

    h5 {
        padding-bottom: 2.5rem
    }


    button {
    }

    #totalCost {
        text-align: right !important;
    }
</style>


<h2>Корзина покупок</h2>
@if (User.Identity.IsAuthenticated)
{
    <div class="alert alert-primary" role="alert">
        Чтобы добавить товары, которые были у Вас в корзине до входа в аккаунт, нажмите <a href="#" onclick="ImportItems()">сюда</a>.
    </div>
}
@if (!Model.CartItem.Any())
{
    <hr />
    <h3>В вашей корзине пока ничего нет :(</h3>
    <h5>Но вы можете пополнить её прямо <a href="~/">сейчас.</a></h5>
    <div class="d-flex justify-content-center"><img id="feelings" style="width:30rem" src="~/images/sadface.png" /></div>
}
else

{
    <div class="toast" data-delay="3000" style="position: absolute; top: 5.2rem; right: 2rem;">
        <div class="toast-header">
            <strong class="mr-auto">Wahama Shop</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Изменения в корзине применены успешно!
        </div>
    </div>

    <table class="table table-responsive">
        <thead>
            <tr>
                <th>
                    Изображение
                </th>
                <th>
                    Наименование
                </th>
                <th>
                    Количество
                </th>
                <th>Цена</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>



            @foreach (var item in Model.CartItem)
            {
                string inputId = "quantityInput" + item.ProductId.ToString();
                <tr>
                    <td>
                        <img style="width:10.5rem" src="@Html.DisplayFor(modelItem => modelItem.ImageSources[item.Product.Id])" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        <input type="number" style="width:70%" class="quantity" id="@inputId" value="@item.Quantity" />
                    </td>
                    <td class="price">
                        @Html.DisplayFor(modelItem => item.Product.Price)
                    </td>
                    <td>
                        <a onclick="ChangeQuantity(@item.ProductId, @item.Quantity)">Обновить</a>
                    </td>
                    <td>
                        <a onclick="RemoveFromCart(@item.ProductId)">Удалить</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <h3 id="totalCost"></h3>

    <div class="d-flex justify-content-end">
        <button class="btn btn-primary">Оформить заказ</button>
    </div>
}

<script>
    $(document).ready(GetTotalCost());
    function ImportItems() {
        $.ajax({
            url: '@Url.Content("~/")' + 'ShoppingCarts/ImportUnauthorizedCartToAccount',
            contentType: "application/x-www-form/urlencoded",
            type: "POST",
            datatype: "json",
             error: function (xmlHttpRequest, errorText, thrownError) {
                alert(xmlHttpRequest + "|" + errorText + "|" + thrownError);
            },
            success: function (data) {
                location.reload();
            }
        })
    }
    function GetTotalCost() {
        var param = {
            userId: "CurrentUser"
        };
        $.ajax({
            url: '@Url.Content("~/")' + 'ShoppingCarts/GetTotalCost',
            contentType: "application/x-www-form-urlencoded",
            type: "POST",
            datatype: "json",
            data: param,
            error: function (xmlHttpRequest, errorText, thrownError) {
                alert(xmlHttpRequest + "|" + errorText + "|" + thrownError);
            },
            success: function (data) {
                if (data != null) {

                    $('#totalCost').html("Сумма: " + data + " ₽");
                    $('#totalCost').addClass("ml-auto").css("text-align:right");

                }
            }
        });
    }

    function RemoveFromCart(productId) {
        var _this = $(this);
        var param = {
            quantityDifference: null,
            productId: productId

        };
        $.ajax({
            url: '@Url.Content("~/")' + 'ShoppingCarts/RemoveFromCart',
            contentType: "application/x-www-form-urlencoded",
            type: "POST",
            datatype: "json",

            data: param,
            error: function (xmlHttpRequest, errorText, thrownError) {
                alert(xmlHttpRequest + "|" + errorText + "|" + thrownError);
            },
            success: function (data) {
                if (data != null) {

                    GetTotalCost();
                    location.reload()
                    $('.toast').toast('show');
                }
            }
        });
    }

    function ChangeQuantity(productId, oldQuantity) {
        var _this = $(this);
        var qElementId = "#quantityInput" + productId;
        var param = {
            quantityDifference:$(qElementId).val() - oldQuantity,
            productId: productId
        };
        $.ajax({
            url: '@Url.Content("~/")' + 'ShoppingCarts/RemoveFromCart',
            contentType: "application/x-www-form-urlencoded",
            type: "POST",
            datatype: "json",
            data: param,
            error: function (xmlHttpRequest, errorText, thrownError) {
                alert(xmlHttpRequest + "|" + errorText + "|" + thrownError);
            },
            success: function (data) {
                if (data != null) {
                    location.reload();
                    $('.toast').toast('show');
                }
            },

        });
    }



</script>

Views/ShoppingCarts/Order.cshtml
@model OrderViewModel

@{
    ViewData["Title"] = "Оформление заказа";
}

<style>
    form {
        margin-top: 5rem;
    }

    input {
        margin-bottom: 1.5rem;
    }
    .table td {
        vertical-align: middle;
    }

    .table th {
        width: 15%;
    }

    a {
        cursor: pointer;
    }

    

    h2 {
        padding-bottom: 1.5rem;
    }

    h3 {
        margin-top: 1.5rem;
        padding-bottom: 1rem
    }

    h5 {
        padding-bottom: 2.5rem
    }


    button {
    }

    #totalCost {
        text-align: right !important;
    }
</style>

<h2>Оформление заказа</h2>


<table class="table table-responsive">
    <thead>
        <tr>

            <th>
                Изображение
            </th>
            <th>
                Наименование
            </th>
            <th>
                Кол-во
            </th>
            <th>Цена</th>

        </tr>
    </thead>

    <tbody>



        @foreach (var item in Model.CartItem)
        {
            string inputId = "quantityInput" + item.ProductId.ToString();
            <tr>
                <td>
                    <img style="width:8.5rem" src="@Html.DisplayFor(modelItem => modelItem.ImageSources[item.Product.Id])" />
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>

                <td>
                    @item.Quantity
                </td>

                <td class="price">
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
            </tr>
        }
    </tbody>
</table>



<h3 id="totalCost">Итого: @ViewBag.Total ₽</h3>
<hr />
<form asp-action="MakeOrder" asp-controller="ShoppingCarts" asp-anti-forgery="true">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div>
            <label asp-for="Customer.FirstName">Имя</label><br />
            <input type="text" asp-for="Customer.FirstName" />
            <span asp-validation-for="Customer.FirstName" />

        </div>
        <div>
            <label asp-for="Customer.LastName">Фамилия</label><br />
            <input type="text" asp-for="Customer.LastName" />
            <span asp-validation-for="Customer.LastName" />
        </div>
        <div>
            <label asp-for="Customer.Phone">Номер телефона</label><br />
            <input type="tel" asp-for="Customer.Phone" />
            <span asp-validation-for="Customer.Phone" />
        </div>


        <div>
            <label asp-for="Address.Country">Страна</label><br />
            <input type="text" asp-for="Address.Country" />
            <span asp-validation-for="Address.Country" />
        </div>
        <div>
            <label asp-for="Address.City">Город</label><br />
            <input type="text" asp-for="Address.City" />
            <span asp-validation-for="Address.City" />
        </div>
        <div>
            <label asp-for="Address.Street">Улица</label><br />
            <input type="text" asp-for="Address.Street" />
            <span asp-validation-for="Address.Street" />
        </div>
        <div>
            <label asp-for="Address.Building">Дом</label><br />
            <input type="text" asp-for="Address.Building" />
            <span asp-validation-for="Address.Building" />
        </div>
        <div>
            <label asp-for="Address.Flat">Квартира</label><br />
            <input type="text" asp-for="Address.Flat" />
            <span asp-validation-for="Address.Flat" />
        </div>
        <div>
            <label asp-for="Address.Floor">Этаж</label><br />
            <input type="text" asp-for="Address.Floor" />
            <span asp-validation-for="Address.Floor" />
        </div>
        <div>
            <label asp-for="Address.Zip">Индекс</label><br />
            <input type="text" asp-for="Address.Zip" />
            <span asp-validation-for="Address.Zip" />
        </div>
        <div>
            <label asp-for="Address.Station">Ближайшая ст. метро</label><br />
            <input type="text" asp-for="Address.Station" />
            <span asp-validation-for="Address.Station" />
        </div>

        <input type="submit" value="Оформить заказ" />
    </div>
</form>

Views/ShoppingCarts/OrderSuccess.cshtml
@{
    ViewData["Title"] = "Заказ оформлен";
}
    <style>
        h3{
            padding-bottom:3rem;
        }
    </style>
<h1 class="text-center">Ура!</h1>
<h3 class="text-center">Мы получили Ваш заказ и начали его обработку.</h3>
<h5 class="text-center">Заказ #@ViewBag.OrderId</h5>